version: '3'

services:
  mongo:
    image: bitnami/mongodb:latest
    ports:
      - "27017:27017"
    hostname: mongo
    environment:
      MONGODB_USERNAME: test
      MONGODB_PASSWORD: 111222
      MONGODB_ROOT_PASSWORD: 111222
      MONGODB_DATABASE: test
    volumes:
      - ./config:/opt/bitnami/mongodb/conf
      - ./db:/bitnami/mongodb