version: '3'

services:
  fix-mongodb-permissions:
    image: 'bitnami/mongodb:latest'
    user: root
    command: chown -R 1001:1001 /bitnami && chown -R 1001:1001 /bitnami/*
    volumes:
    - ./db:/bitnami
  mongoS1:
    container_name: mongodb_shard1
    image: bitnami/mongodb:latest
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 3G
    restart: unless-stopped
    expose:
      - "27017"
    hostname: mongos1
    environment:
      MONGODB_ROOT_PASSWORD: 111222
      MONGODB_EXTRA_FLAGS: --wiredTigerCacheSizeGB=2
    volumes:
      - ./config/shard:/opt/bitnami/mongodb/conf
      - ./db/db1/svr1:/bitnami/mongodb
  mongoS2:
    container_name: mongodb_shard2
    image: bitnami/mongodb:latest
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 3G
    environment:
      MONGODB_EXTRA_FLAGS: --wiredTigerCacheSizeGB=2
    restart: unless-stopped
    expose:
      - "27017"
    hostname: mongos2
    volumes:
      - ./config/shard:/opt/bitnami/mongodb/conf
      - ./db/db1/svr2:/bitnami/mongodb
  mongoS3:
    container_name: mongodb_shard3
    image: bitnami/mongodb:latest
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 3G
    environment:
      MONGODB_EXTRA_FLAGS: --wiredTigerCacheSizeGB=2
    restart: unless-stopped
    expose:
      - "27017"
    hostname: mongos3
    volumes:
      - ./config/shard2:/opt/bitnami/mongodb/conf
      - ./db/db2/svr3:/bitnami/mongodb
  mongoS4:
    container_name: mongodb_shard4
    image: bitnami/mongodb:latest
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 3G
    environment:
      MONGODB_EXTRA_FLAGS: --wiredTigerCacheSizeGB=2
    restart: unless-stopped
    expose:
      - "27017"
    hostname: mongos4
    volumes:
      - ./config/shard2:/opt/bitnami/mongodb/conf
      - ./db/db2/svr4:/bitnami/mongodb
  mongoCfg1:
    container_name: mongodb_config1
    image: bitnami/mongodb:latest
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
    restart: unless-stopped
    # ports:
    #   - "27019:27019"
    expose:
      - "27017"
    hostname: mongoCfg1
    # environment:
    #   MONGODB_USERNAME: test
    #   MONGODB_PASSWORD: 111222
    #   MONGODB_ROOT_PASSWORD: 111222
    #   MONGODB_DATABASE: test
    volumes:
      - ./config/config:/opt/bitnami/mongodb/conf
      - ./db/db1/config1:/bitnami/mongodb
  mongoCfg2:
    container_name: mongodb_config2
    image: bitnami/mongodb:latest
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
    restart: unless-stopped
    expose:
      - "27017"
    hostname: mongoCfg2
    volumes:
      - ./config/config:/opt/bitnami/mongodb/conf
      - ./db/db2/config2:/bitnami/mongodb
  mongos:
    container_name: mongos
    image: bitnami/mongodb:latest
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 300M
    hostname: mongos
    restart: unless-stopped
    depends_on:
      - mongoCfg1 
      - mongoCfg2
    command: mongos --configdb partdioConf/mongoCfg1:27017,mongoCfg2:27017 --port 3000 --bind_ip 0.0.0.0 
    ports:
        - "27023:3000"
    # expose:
    #   - "27017"

